# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51d5c017249731ddcf247a2b6c9a6fb7"
name = "Subscriptions Manager"
application_url = "https://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customer_redact"
  compliance_topics = [ "customers/data_request", "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "selling_plan_groups/create", "selling_plan_groups/update" ]
  uri = "/webhooks/selling_plan_groups/create_or_update"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/failure" ]
  uri = "/webhooks/subscription_billing_attempts/failure"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/success" ]
  uri = "/webhooks/subscription_billing_attempts/success"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_cycles/skip" ]
  uri = "/webhooks/subscription_billing_cycles/skip"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/activate" ]
  uri = "/webhooks/subscription_contracts/activate"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/cancel" ]
  uri = "/webhooks/subscription_contracts/cancel"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "/webhooks/subscription_contracts/create"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/pause" ]
  uri = "/webhooks/subscription_contracts/pause"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,write_checkouts,read_checkouts,read_customers,write_customers,write_customer_payment_methods,read_customer_payment_methods,write_draft_orders,read_draft_orders,read_orders,write_orders,read_payment_customizations,write_payment_customizations,read_products,write_products,write_own_subscription_contracts,read_own_subscription_contracts,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false

[app_preferences]
url = "https://localhost:3000/settings"
